name: build-and-publish-blobclient

env:
  PROJECT: Core.BlobStorage.Client
  NUGET_USER: hugolamounier
  NUGET_SOURCE: https://nuget.pkg.github.com/hugolamounier/index.json

on: push

jobs:
  build-and-publish:
    
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Nuget config
        shell: bash
        run: dotnet nuget add source $NUGET_SOURCE -n github -u $NUGET_USER -p ${{ secrets.TOKEN }} --store-password-in-clear-text

      - name: Restore
        run: dotnet restore

      - name: Build release
        run: dotnet build -c Release

      - name: Pack projects
        run: dotnet pack src/$PROJECT/$PROJECT.csproj $PKG_VERSION_SUFFIX -c Release

      - name: Push packages
        run: dotnet nuget push "**/*.nupkg" -s github --skip-duplicate
